package io.github.fulizhe.otelstore.core.storage;

import io.github.fulizhe.otelstore.core.config.LocalStoreConfig;
import io.github.fulizhe.otelstore.core.model.LogRecordEntry;
import io.github.fulizhe.otelstore.core.model.MetricPointEntry;
import io.github.fulizhe.otelstore.core.model.SpanRecord;
import io.github.fulizhe.otelstore.core.util.ThrottledLogger;
import java.io.Closeable;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * 本地遥测存储：H2 内存库（表头）+ 两个环形文件（载荷）。
 *
 * <p><b>不引用任何 {@code io.opentelemetry.*}</b>：入参是 {@code core.model} 里的
 * JDK 原生类型（见 ADR-1 的分层规则与 {@code core} 不许 import OTel 的硬规则）。
 *
 * <h3>线程模型：所有 DB 访问串行在一把锁下</h3>
 *
 * <p>三条 drainer 线程各写各的表，读口线程还会读 —— 而嵌入式 H2 的单个
 * {@code Connection} 不是线程安全的。与其开四条连接再各自处理事务可见性，
 * 不如一把锁把全部 DB 访问串起来。代价是写与写之间会互相排队，但每次操作是微秒级的
 * 内存写，量级上无关紧要；而收益是彻底没有"两个线程共用一个连接"这类 bug。
 *
 * <p>注意这条锁<b>不会</b>拖住业务线程：三个 drainer 都在队列后面，
 * 采集线程只做一次 {@code offer}（ADR-1 头号约束）。
 *
 * <h3>有界靠三样东西，不靠第四样</h3>
 *
 * <ul>
 *   <li>表头侧：行数水位（{@code rows.traces} / {@code rows.logs} / {@code rows.metrics}），
 *       超了按 {@code id} 从最旧开始删 —— 行按插入顺序写、按最旧淘汰，所以 {@code id} 序≈时间序，
 *       这也是 ADR-2 决定"不建时间索引"的前提。</li>
 *   <li>载荷侧：环形文件的固定字节数（{@code capped.traces.bytes} / {@code capped.logs.bytes}）。</li>
 *   <li>单条侧：{@code max.payload.bytes}，超了丢载荷但<b>保住表头行</b>
 *       （否则列表页会凭空少一行，而"少了"正是 ADR-3 要能解释的东西）。</li>
 *   <li>metrics 不走环形文件，因此它的有界<b>只能</b>来自行数水位。</li>
 * </ul>
 */
public final class LocalStore implements AutoCloseable {

    /**
     * 内存库名。固定名字即可 —— H2 内存库天然进程私有，而"同一 dataDir 只会有一个实例"
     * 是 ADR-4 声明的作用域前提。
     */
    private static final String DEFAULT_DB_NAME = "otel-local-telemetry-store";

    /** traces 环文件。 */
    static final String TRACES_RING_FILE = "traces.capped";
    /** logs 环文件。 */
    static final String LOGS_RING_FILE = "logs.capped";

    /**
     * 表结构，与 ADR-2 的三张表 + 字典表一一对应。
     *
     * <p>索引只有 ADR-2 定的那些：{@code span} 与 {@code log_record} 各按 trace/span 建，
     * <b>都不建时间索引</b>（时间范围查询靠 {@code id} 序）。{@code metric_point} 另建
     * {@code (metric_name, ts)} —— 它没有 payload，时间序就是唯一的查法，
     * 不建索引等于每次查询都顺序扫。
     *
     * <p>{@code metric_value} 不叫 {@code value}：{@code VALUE} 是 H2 2.x 的保留字，
     * 想用就得处处加引号、加引号又会让标识符变成大小写敏感 —— 收益为零、坑一堆。
     */
    private static final String[] DDL = {
            "CREATE TABLE IF NOT EXISTS resource_dict ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "attributes_hash VARCHAR(64) NOT NULL, "
                    + "attributes VARCHAR(8192) NOT NULL, "
                    + "attr_count INT NOT NULL, "
                    + "CONSTRAINT uq_resource_dict_hash UNIQUE (attributes_hash))",

            "CREATE TABLE IF NOT EXISTS span ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "trace_id VARCHAR(32) NOT NULL, "
                    + "span_id VARCHAR(16) NOT NULL, "
                    + "parent_span_id VARCHAR(16) NOT NULL, "
                    + "name VARCHAR(512) NOT NULL, "
                    + "kind INT NOT NULL, "
                    + "start_time BIGINT NOT NULL, "
                    + "end_time BIGINT NOT NULL, "
                    + "status_code INT NOT NULL, "
                    + "status_message VARCHAR(1024), "
                    + "scope_name VARCHAR(255), "
                    + "scope_version VARCHAR(64), "
                    + "resource_id BIGINT NOT NULL, "
                    + "attr_count INT NOT NULL, "
                    + "event_count INT NOT NULL, "
                    + "payload_id BIGINT)",
            "CREATE INDEX IF NOT EXISTS idx_span_trace ON span(trace_id)",

            "CREATE TABLE IF NOT EXISTS log_record ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "trace_id VARCHAR(32), "
                    + "span_id VARCHAR(16), "
                    + "severity_number INT NOT NULL, "
                    + "severity_text VARCHAR(64), "
                    + "timestamp BIGINT NOT NULL, "
                    + "observed_timestamp BIGINT NOT NULL, "
                    + "body_preview VARCHAR(1024), "
                    + "scope_name VARCHAR(255), "
                    + "scope_version VARCHAR(64), "
                    + "resource_id BIGINT NOT NULL, "
                    + "attr_count INT NOT NULL, "
                    + "payload_id BIGINT)",
            "CREATE INDEX IF NOT EXISTS idx_log_trace ON log_record(trace_id)",
            "CREATE INDEX IF NOT EXISTS idx_log_span ON log_record(span_id)",

            "CREATE TABLE IF NOT EXISTS metric_point ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "metric_name VARCHAR(255) NOT NULL, "
                    + "data_type VARCHAR(16) NOT NULL, "
                    + "ts BIGINT NOT NULL, "
                    + "resource_id BIGINT NOT NULL, "
                    + "scope_name VARCHAR(255), "
                    + "scope_version VARCHAR(64), "
                    + "attr_key VARCHAR(64) NOT NULL, "
                    + "unit VARCHAR(32), "
                    + "description VARCHAR(512), "
                    + "metric_value DOUBLE, "
                    + "metric_count BIGINT, "
                    + "metric_sum DOUBLE, "
                    + "detail VARCHAR(8192))",
            "CREATE INDEX IF NOT EXISTS idx_metric_name_ts ON metric_point(metric_name, ts)",
            "CREATE INDEX IF NOT EXISTS idx_metric_attr ON metric_point(attr_key)",
    };

    private final LocalStoreConfig config;
    private final Connection conn;
    private final ResourceDictionary resources;
    private final PayloadRing traceRing;
    private final PayloadRing logRing;
    private final Object lock = new Object();

    /** 行数水位的当前存量。ADR-4 保证每次启动都是空的，所以能从 0 起算而不必先 COUNT 一遍。 */
    private long spanRows;
    private long logRows;
    private long metricRows;
    private long evictedSpanRows;
    private long evictedLogRows;
    private long evictedMetricRows;
    private long storeErrors;

    public LocalStore(final LocalStoreConfig config) throws SQLException, IOException {
        this(config, DEFAULT_DB_NAME);
    }

    /**
     * @param dbName H2 内存库名。生产固定；测试用它给每个用例一个独立库，避免互相看见数据。
     */
    LocalStore(final LocalStoreConfig config, final String dbName) throws SQLException, IOException {
        this.config = config;
        final File dir = new File(config.getDataDir());
        if (!dir.isDirectory() && !dir.mkdirs()) {
            throw new IOException("数据目录建不出来：" + dir.getAbsolutePath());
        }
        this.conn = DriverManager.getConnection("jdbc:h2:mem:" + dbName + ";DB_CLOSE_DELAY=-1");
        this.conn.setAutoCommit(true);
        createSchema();
        this.resources = new ResourceDictionary(conn);
        this.traceRing = new PayloadRing("traces", new File(dir, TRACES_RING_FILE),
                config.getCappedTracesBytes(), config.getMaxPayloadBytes());
        this.logRing = new PayloadRing("logs", new File(dir, LOGS_RING_FILE),
                config.getCappedLogsBytes(), config.getMaxPayloadBytes());
    }

    /**
     * 建表。
     *
     * <p>先 {@code DROP ALL OBJECTS}：内存库在同一个 JVM 里若已存在同名的（例如应用重起了
     * 一个 Spring context 而上一次的 {@code LocalStore} 没关干净），"重启即清空"就得靠这一步兑现。
     * H2 内存库不会跨进程存活，所以这不影响 ADR-4 的语义，只是把"进程内重建"也纳入同一口径。
     */
    private void createSchema() throws SQLException {
        synchronized (lock) {
            final Statement st = conn.createStatement();
            try {
                st.execute("DROP ALL OBJECTS");
                for (int i = 0; i < DDL.length; i++) {
                    st.execute(DDL[i]);
                }
            } finally {
                st.close();
            }
        }
    }

    // ============================ 写

    /**
     * 落一条 span：表头行进 H2，载荷进 traces 环。
     *
     * @throws StoreException 任一环节失败。调用方（drainer）只计数，不外抛。
     */
    public void store(final SpanRecord record) {
        if (record == null) {
            return;
        }
        synchronized (lock) {
            try {
                final long resourceId = resources.intern(record.getResource());
                // 载荷先写：环写失败也要保住表头行，反过来会让"库里没有"和"载荷丢了"两种
                // 情况混成同一个现象，而分清它们正是 ADR-3 的目的。
                final long payloadId = traceRing.write(record.getPayload());
                final PreparedStatement ps = conn.prepareStatement(
                        "INSERT INTO span (trace_id, span_id, parent_span_id, name, kind, start_time, end_time,"
                                + " status_code, status_message, scope_name, scope_version, resource_id,"
                                + " attr_count, event_count, payload_id)"
                                + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                        PreparedStatement.RETURN_GENERATED_KEYS);
                try {
                    ps.setString(1, nz(record.getTraceId()));
                    ps.setString(2, nz(record.getSpanId()));
                    ps.setString(3, nz(record.getParentSpanId()));
                    ps.setString(4, nz(record.getName()));
                    ps.setInt(5, record.getKind());
                    ps.setLong(6, record.getStartEpochNanos());
                    ps.setLong(7, record.getEndEpochNanos());
                    ps.setInt(8, record.getStatusCode());
                    ps.setString(9, record.getStatusMessage());
                    ps.setString(10, record.getScopeName());
                    ps.setString(11, record.getScopeVersion());
                    ps.setLong(12, resourceId);
                    ps.setInt(13, record.getAttributeCount());
                    ps.setInt(14, record.getEventCount());
                    setNullableLong(ps, 15, payloadId);
                    ps.executeUpdate();
                } finally {
                    ps.close();
                }
                spanRows++;
                if (spanRows > config.getRowsTraces()) {
                    final long excess = spanRows - config.getRowsTraces();
                    evictOldest("span", excess);
                    evictedSpanRows += excess;
                    spanRows -= excess;
                }
            } catch (final SQLException e) {
                throw fail("span", e);
            }
        }
    }

    /** 落一条日志记录：表头行进 H2，载荷进 logs 环。 */
    public void store(final LogRecordEntry entry) {
        if (entry == null) {
            return;
        }
        synchronized (lock) {
            try {
                final long resourceId = resources.intern(entry.getResource());
                final long payloadId = logRing.write(entry.getPayload());
                final PreparedStatement ps = conn.prepareStatement(
                        "INSERT INTO log_record (trace_id, span_id, severity_number, severity_text, timestamp,"
                                + " observed_timestamp, body_preview, scope_name, scope_version, resource_id,"
                                + " attr_count, payload_id)"
                                + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");
                try {
                    ps.setString(1, blankToNull(entry.getTraceId()));
                    ps.setString(2, blankToNull(entry.getSpanId()));
                    ps.setInt(3, entry.getSeverityNumber());
                    ps.setString(4, blankToNull(entry.getSeverityText()));
                    ps.setLong(5, entry.getTimestampEpochNanos());
                    ps.setLong(6, entry.getObservedTimestampEpochNanos());
                    ps.setString(7, entry.getBodyPreview());
                    ps.setString(8, entry.getScopeName());
                    ps.setString(9, entry.getScopeVersion());
                    ps.setLong(10, resourceId);
                    ps.setInt(11, entry.getAttributeCount());
                    setNullableLong(ps, 12, payloadId);
                    ps.executeUpdate();
                } finally {
                    ps.close();
                }
                logRows++;
                if (logRows > config.getRowsLogs()) {
                    final long excess = logRows - config.getRowsLogs();
                    evictOldest("log_record", excess);
                    evictedLogRows += excess;
                    logRows -= excess;
                }
            } catch (final SQLException e) {
                throw fail("log_record", e);
            }
        }
    }

    /**
     * 落一个指标数据点。
     *
     * <p>没有载荷环节 —— metrics 不走环形文件（ADR-2），桶与分位数直接落进 {@code detail} 列。
     */
    public void store(final MetricPointEntry point) {
        if (point == null) {
            return;
        }
        synchronized (lock) {
            try {
                final long resourceId = resources.intern(point.getResource());
                final String attrKey = CanonicalAttributes.hash(point.getAttributes());
                final PreparedStatement ps = conn.prepareStatement(
                        "INSERT INTO metric_point (metric_name, data_type, ts, resource_id, scope_name,"
                                + " scope_version, attr_key, unit, description, metric_value, metric_count,"
                                + " metric_sum, detail)"
                                + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)");
                try {
                    ps.setString(1, nz(point.getMetricName()));
                    ps.setString(2, point.getKind().name());
                    ps.setLong(3, point.getTimestampEpochNanos());
                    ps.setLong(4, resourceId);
                    ps.setString(5, point.getScopeName());
                    ps.setString(6, point.getScopeVersion());
                    ps.setString(7, attrKey);
                    ps.setString(8, blankToNull(point.getUnit()));
                    ps.setString(9, blankToNull(point.getDescription()));
                    if (point.getKind() == MetricPointEntry.MetricKind.GAUGE
                            || point.getKind() == MetricPointEntry.MetricKind.SUM) {
                        ps.setDouble(10, point.getValue());
                    } else {
                        ps.setNull(10, java.sql.Types.DOUBLE);
                    }
                    if (point.getKind() == MetricPointEntry.MetricKind.HISTOGRAM
                            || point.getKind() == MetricPointEntry.MetricKind.SUMMARY) {
                        ps.setLong(11, point.getCount());
                        ps.setDouble(12, point.getSum());
                    } else {
                        ps.setNull(11, java.sql.Types.BIGINT);
                        ps.setNull(12, java.sql.Types.DOUBLE);
                    }
                    ps.setString(13, point.getDetail());
                    ps.executeUpdate();
                } finally {
                    ps.close();
                }
                metricRows++;
                if (metricRows > config.getRowsMetrics()) {
                    final long excess = metricRows - config.getRowsMetrics();
                    evictOldest("metric_point", excess);
                    evictedMetricRows += excess;
                    metricRows -= excess;
                }
            } catch (final SQLException e) {
                throw fail("metric_point", e);
            }
        }
    }

    /**
     * 删掉最旧的 {@code n} 行。
     *
     * <p>先查第 n 行的 id 再按 {@code id <= 那个值} 删，而不是把 id 列表塞进 {@code IN}：
     * 淘汰量可能是几千行，{@code IN} 会把一条 SQL 撑到超出 H2 的表达式上限。
     */
    private void evictOldest(final String table, final long n) throws SQLException {
        if (n <= 0L) {
            return;
        }
        final PreparedStatement ps = conn.prepareStatement(
                "SELECT MAX(id) FROM (SELECT id FROM " + table + " ORDER BY id ASC FETCH FIRST "
                        + n + " ROWS ONLY) oldest");
        long cutoff;
        try {
            final ResultSet rs = ps.executeQuery();
            try {
                if (!rs.next()) {
                    return;
                }
                cutoff = rs.getLong(1);
                if (rs.wasNull()) {
                    return;
                }
            } finally {
                rs.close();
            }
        } finally {
            ps.close();
        }
        final PreparedStatement del = conn.prepareStatement("DELETE FROM " + table + " WHERE id <= ?");
        try {
            del.setLong(1, cutoff);
            del.executeUpdate();
        } finally {
            del.close();
        }
    }

    // ============================ 读

    /** span 表行数。 */
    public int countSpans() throws SQLException {
        return countRows("span");
    }

    /** log_record 表行数。 */
    public int countLogs() throws SQLException {
        return countRows("log_record");
    }

    /** metric_point 表行数。 */
    public int countMetrics() throws SQLException {
        return countRows("metric_point");
    }

    /** resource_dict 行数。 */
    public int countResources() throws SQLException {
        return resources.rowCount();
    }

    private int countRows(final String table) throws SQLException {
        synchronized (lock) {
            final PreparedStatement ps = conn.prepareStatement("SELECT COUNT(*) FROM " + table);
            try {
                final ResultSet rs = ps.executeQuery();
                try {
                    return rs.next() ? rs.getInt(1) : 0;
                } finally {
                    rs.close();
                }
            } finally {
                ps.close();
            }
        }
    }

    /**
     * 最近的 span 表头行（新到旧），不含载荷。
     *
     * <p>返回 {@code List<Map<String,Object>>} 而不是自定义行类型：读口要跨 ClassLoader
     * 交给 JMX / HTTP 侧序列化，只能出 JDK 原生类型（ADR-1 的读口约定）。
     */
    public List<Map<String, Object>> recentSpans(final int limit) throws SQLException {
        return query("SELECT id, trace_id, span_id, parent_span_id, name, kind, start_time, end_time,"
                        + " status_code, scope_name, scope_version, resource_id, attr_count, event_count,"
                        + " payload_id FROM span ORDER BY id DESC FETCH FIRST " + positive(limit) + " ROWS ONLY",
                SPAN_COLUMNS);
    }

    /** 某个 trace 的全部 span（按开始时间排），用来在详情页把一个 trace 拼起来。 */
    public List<Map<String, Object>> spansOfTrace(final String traceId) throws SQLException {
        final PreparedStatement ps;
        synchronized (lock) {
            ps = conn.prepareStatement("SELECT id, trace_id, span_id, parent_span_id, name, kind, start_time,"
                    + " end_time, status_code, scope_name, scope_version, resource_id, attr_count, event_count,"
                    + " payload_id FROM span WHERE trace_id = ? ORDER BY start_time ASC");
            try {
                ps.setString(1, traceId == null ? "" : traceId);
                return read(ps, SPAN_COLUMNS);
            } finally {
                ps.close();
            }
        }
    }

    /** 最近的日志表头行（新到旧），不含载荷。 */
    public List<Map<String, Object>> recentLogs(final int limit) throws SQLException {
        return query("SELECT id, trace_id, span_id, severity_number, severity_text, timestamp,"
                        + " body_preview, scope_name, scope_version, resource_id, attr_count, payload_id"
                        + " FROM log_record ORDER BY id DESC FETCH FIRST " + positive(limit) + " ROWS ONLY",
                LOG_COLUMNS);
    }

    /** 某个指标名最近的点（新到旧）。 */
    public List<Map<String, Object>> recentMetricPoints(final String metricName, final int limit)
            throws SQLException {
        final PreparedStatement ps;
        synchronized (lock) {
            ps = conn.prepareStatement("SELECT id, metric_name, data_type, ts, resource_id, scope_name,"
                    + " scope_version, attr_key, unit, metric_value, metric_count, metric_sum, detail"
                    + " FROM metric_point WHERE metric_name = ? ORDER BY ts DESC, id DESC FETCH FIRST "
                    + positive(limit) + " ROWS ONLY");
            try {
                ps.setString(1, metricName == null ? "" : metricName);
                return read(ps, METRIC_COLUMNS);
            } finally {
                ps.close();
            }
        }
    }

    /**
     * 按行 id 读回 span 的载荷。
     *
     * <p>{@code payload_id} 走 {@code wasNull()} 判定 —— 这是 ADR-2 第 1 条坑：
     * 载荷被拒写时这一列是 NULL，而 {@code 0} 恰好是合法的首个逻辑偏移。
     * 用 {@code getLong()} 的返回值判空会把"没有载荷"误报成"指向环里最老那块"，
     * 读回来的是一条**别人的**记录，且没有任何报错。
     *
     * @return 载荷字节；没有载荷或已被环覆盖时为 {@code null}（后者是<b>过期</b>，预期行为）
     */
    public byte[] spanPayload(final long spanId) throws SQLException {
        final long blockId;
        synchronized (lock) {
            final PreparedStatement ps = conn.prepareStatement("SELECT payload_id FROM span WHERE id = ?");
            try {
                ps.setLong(1, spanId);
                final ResultSet rs = ps.executeQuery();
                try {
                    if (!rs.next()) {
                        return null;
                    }
                    blockId = rs.getLong(1);
                    if (rs.wasNull()) {
                        return null;
                    }
                } finally {
                    rs.close();
                }
            } finally {
                ps.close();
            }
        }
        return traceRing.read(blockId);
    }

    /** 按行 id 读回日志记录的载荷；{@code payload_id} 的 NULL 判定同 {@link #spanPayload(long)}。 */
    public byte[] logPayload(final long logId) throws SQLException {
        final long blockId;
        synchronized (lock) {
            final PreparedStatement ps = conn.prepareStatement("SELECT payload_id FROM log_record WHERE id = ?");
            try {
                ps.setLong(1, logId);
                final ResultSet rs = ps.executeQuery();
                try {
                    if (!rs.next()) {
                        return null;
                    }
                    blockId = rs.getLong(1);
                    if (rs.wasNull()) {
                        return null;
                    }
                } finally {
                    rs.close();
                }
            } finally {
                ps.close();
            }
        }
        return logRing.read(blockId);
    }

    /** 读一份 Resource 的规范化文本（字典表那一列的原文）。 */
    public String resourceAttributes(final long resourceId) throws SQLException {
        synchronized (lock) {
            final PreparedStatement ps = conn.prepareStatement(
                    "SELECT attributes FROM resource_dict WHERE id = ?");
            try {
                ps.setLong(1, resourceId);
                final ResultSet rs = ps.executeQuery();
                try {
                    return rs.next() ? rs.getString(1) : null;
                } finally {
                    rs.close();
                }
            } finally {
                ps.close();
            }
        }
    }

    private List<Map<String, Object>> query(final String sql, final String[] columns) throws SQLException {
        synchronized (lock) {
            final PreparedStatement ps = conn.prepareStatement(sql);
            try {
                return read(ps, columns);
            } finally {
                ps.close();
            }
        }
    }

    /**
     * 把结果集摊成 JDK 原生 Map。
     *
     * <p>列名统一走 {@code getColumnLabel} 并转小写：H2 默认把未加引号的标识符折成大写，
     * 不统一的话读口那边会出现 {@code TRACE_ID} / {@code traceId} 两种命名。
     */
    private List<Map<String, Object>> read(final PreparedStatement ps, final String[] columns)
            throws SQLException {
        final List<Map<String, Object>> rows = new ArrayList<Map<String, Object>>();
        final ResultSet rs = ps.executeQuery();
        try {
            while (rs.next()) {
                final Map<String, Object> row = new LinkedHashMap<String, Object>();
                for (int i = 0; i < columns.length; i++) {
                    row.put(columns[i], rs.getObject(i + 1));
                }
                rows.add(row);
            }
        } finally {
            rs.close();
        }
        return rows;
    }

    private static final String[] SPAN_COLUMNS = {
            "id", "traceId", "spanId", "parentSpanId", "name", "kind", "startTime", "endTime",
            "statusCode", "scopeName", "scopeVersion", "resourceId", "attrCount", "eventCount", "payloadId"};
    private static final String[] LOG_COLUMNS = {
            "id", "traceId", "spanId", "severityNumber", "severityText", "timestamp",
            "bodyPreview", "scopeName", "scopeVersion", "resourceId", "attrCount", "payloadId"};
    private static final String[] METRIC_COLUMNS = {
            "id", "metricName", "dataType", "ts", "resourceId", "scopeName", "scopeVersion",
            "attrKey", "unit", "metricValue", "metricCount", "metricSum", "detail"};

    // ============================ 快照与生命周期

    /**
     * 组合快照，扁平成 JDK 原生类型。
     *
     * <p><b>token 绝不出现在这里</b>（AGENTS.md 读口的安全姿态）—— 快照里只有存储侧的数字与路径。
     */
    public Map<String, Object> snapshot() {
        final Map<String, Object> m = new LinkedHashMap<String, Object>();
        m.put("dataDir", config.getDataDir());
        m.put("spanRows", Long.valueOf(spanRows));
        m.put("logRows", Long.valueOf(logRows));
        m.put("metricRows", Long.valueOf(metricRows));
        m.put("rowWatermarks", watermarks());
        m.put("evicted", evicted());
        m.put("storeErrors", Long.valueOf(storeErrors));
        m.put("resources", resources.snapshot());
        m.put("traceRing", traceRing.snapshot());
        m.put("logRing", logRing.snapshot());
        return m;
    }

    private Map<String, Object> watermarks() {
        final Map<String, Object> m = new LinkedHashMap<String, Object>();
        m.put("traces", Integer.valueOf(config.getRowsTraces()));
        m.put("logs", Integer.valueOf(config.getRowsLogs()));
        m.put("metrics", Integer.valueOf(config.getRowsMetrics()));
        return m;
    }

    private Map<String, Object> evicted() {
        final Map<String, Object> m = new LinkedHashMap<String, Object>();
        m.put("spans", Long.valueOf(evictedSpanRows));
        m.put("logs", Long.valueOf(evictedLogRows));
        m.put("metrics", Long.valueOf(evictedMetricRows));
        return m;
    }

    /** 数据目录（运维要的就是这个路径，环形文件在里面）。 */
    public String dataDir() {
        return config.getDataDir();
    }

    @Override
    public void close() {
        synchronized (lock) {
            closeQuietly(traceRing);
            closeQuietly(logRing);
            try {
                conn.close();
            } catch (final SQLException e) {
                ThrottledLogger.warn("store-close", "关闭 H2 连接失败：" + e);
            }
        }
    }

    private static void closeQuietly(final Closeable c) {
        try {
            c.close();
        } catch (final IOException e) {
            ThrottledLogger.warn("ring-close", "关闭环形文件失败：" + e);
        }
    }

    private StoreException fail(final String what, final SQLException e) {
        storeErrors++;
        ThrottledLogger.warn("store-failed-" + what, what + " 落库失败，本条丢弃并计入 sinkErrors：" + e);
        return new StoreException(what + " 落库失败", e);
    }

    /**
     * {@code payload_id} 是唯一允许为 NULL 的列（载荷被拒 / 编码失败）。
     * 用 {@code setNull} 而不是塞一个魔数 —— 读侧才能用 {@code wasNull()} 分清"没有载荷"。
     */
    private static void setNullableLong(final PreparedStatement ps, final int index, final long value)
            throws SQLException {
        if (value == PayloadRing.NO_BLOCK) {
            ps.setNull(index, java.sql.Types.BIGINT);
        } else {
            ps.setLong(index, value);
        }
    }

    private static String nz(final String s) {
        return s == null ? "" : s;
    }

    private static String blankToNull(final String s) {
        return s == null || s.isEmpty() ? null : s;
    }

    private static int positive(final int limit) {
        return limit <= 0 ? 1 : limit;
    }
}
